services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    entrypoint: tail -f /dev/null   # <-- THE ULTIMATE OVERRIDE
    ports:
      - "8000:8000"
    restart: always
    environment:
      - ALLOWED_HOSTS=backend,localhost
      - CISO_ASSISTANT_URL=https://localhost:8443
      - DJANGO_DEBUG=True
    volumes:
      - db_data:/code/db

  huey:
    container_name: huey
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      - ALLOWED_HOSTS=backend,localhost
      - CISO_ASSISTANT_URL=https://localhost:8443
      - DJANGO_DEBUG=False
    volumes:
      - db_data:/code/db
    entrypoint:
      - /bin/sh
      - -c
      - |
        poetry run python manage.py run_huey -w 2 --scheduler-interval 60


  frontend:
    build:
      context: ./frontend
    container_name: frontend
    environment:
      - PUBLIC_BACKEND_API_URL=http://backend:8000/api
      - PUBLIC_BACKEND_API_EXPOSED_URL=https://localhost:8443/api
      - PROTOCOL_HEADER=x-forwarded-proto
      - HOST_HEADER=x-forwarded-host
    depends_on:
      backend:
        condition: service_healthy

  caddy:
    container_name: caddy
    image: caddy:2.8.4
    restart: unless-stopped
    ports:
      - 8443:8443
    volumes:
      - caddy_data:/data
    command: |
      sh -c 'echo "https://localhost:8443 {
        reverse_proxy /api/* backend:8000
        reverse_proxy /* frontend:3000
        tls internal
      }" > Caddyfile && caddy run'

volumes:
  db_data:
  caddy_data: